---
- hosts: all
  roles:
    - apt-update
    - usbmount
    - install-commands
    - boot-settings
    - wifi-access-point
    - raspi-signage
  vars:
    WIFI_SSID: 'raspi-signage-{{ ("for random salt" | password_hash("md5") | hash("md5"))[:4] }}'
    WIFI_PASS: '{{ ("for random salt" | password_hash("md5") | hash("md5"))[:16] }}'
    WIFI_CHANNEL: '{{ 13 | random(start=1) }}'
