---
- name: disable unuse services
  become: yes
  systemd:
    name: '{{ item }}'
    state: stopped
    daemon_reload: yes
    enabled: no
  with_items:
    - wpa_supplicant
    - hciuart
    - bluetooth
