---
- name: create signage user
  become: yes
  user:
    name: signage
    groups: audio,video

- name: upload sources
  become: yes
  become_user: signage
  copy:
    src: '{{ item }}'
    dest: /home/signage/raspi-signage/
  with_fileglob:
    - raspi-signage/*.py
    - raspi-signage/*.html
    - raspi-signage/*.txt
    - raspi-signage/logo.png
    - raspi-signage/LICENSE
    - raspi-signage/README.md

- name: change settings
  become: yes
  become_user: signage
  replace: >-
    dest='/home/signage/raspi-signage/config.py'
    regexp='BASE_DIR = ".*"'
    replace='BASE_DIR = "/media/"'

- name: install dependencies
  become: yes
  become_user: signage
  command: pip3 install -r /home/signage/raspi-signage/requirements.txt

- name: make raspi-signage.service
  become: yes
  copy:
    dest: /etc/systemd/system/raspi-signage.service
    src: ../files/raspi-signage.service

- name: enable raspi-signage.service
  become: yes
  systemd:
    name: raspi-signage.service
    state: started
    daemon_reload: yes
    enabled: yes
