---
- name: create signage user
  become: yes
  user:
    name: signage
    groups: audio,video

- name: upload raspi-signage sources
  become: yes
  become_user: signage
  copy:
    src: '{{ item }}'
    dest: /home/signage/raspi-signage/
  with_fileglob:
    - raspi-signage/*.py
    - raspi-signage/*.html
    - raspi-signage/*.txt
    - raspi-signage/LICENSE
    - raspi-signage/README.md

- name: upload assets
  become: yes
  become_user: signage
  copy:
    src: '{{ item }}'
    dest: /home/signage/raspi-signage/assets/
  with_fileglob:
    - raspi-signage/assets/logo.png
    - raspi-signage/assets/icon.ico

- name: upload wait-screen sources
  become: yes
  become_user: signage
  copy:
    src: '{{ item }}'
    dest: /home/signage/wait-screen/
  with_fileglob:
    - wait-screen/*.py
    - wait-screen/*.txt

- name: change movie/image directory
  become: yes
  become_user: signage
  replace:
    dest: /home/signage/raspi-signage/config.py
    regexp: '^BASE_DIR = ".*"$'
    replace: 'BASE_DIR = "/media/"'

- name: change default file to wait screen
  become: yes
  become_user: signage
  replace:
    dest: /home/signage/raspi-signage/config.py
    regexp: '^DEFAULT_FILE = ".*"$'
    replace: 'DEFAULT_FILE = "/var/tmp/wait-screen.png"'

- name: install dependencies
  become: yes
  become_user: signage
  command: 'pip3 install -r {{ item }}'
  vars:
    targets:
      - /home/signage/raspi-signage/requirements.txt
      - /home/signage/wait-screen/requirements.txt
  with_items: '{{ targets }}'

- name: install wait-screen dependencies
  become: yes
  become_user: signage
  command: pip3 install -r /home/signage/wait-screen/requirements.txt

- name: make services
  become: yes
  copy:
    src: '{{ item }}'
    dest: /etc/systemd/system/
  with_fileglob:
    - '*.service'

- name: enable services
  become: yes
  systemd:
    name: '{{ item }}'
    state: restarted
    daemon_reload: yes
    enabled: yes
  vars:
    services:
      - raspi-signage.service
      - wait-screen.service
  with_items: '{{ services }}'
