---
- name: disable TTY
  become: yes
  systemd:
    name: '{{ item }}'
    state: stopped
    daemon_reload: yes
    enabled: no
  vars:
    targets: 
      - 'getty@tty1.service'
      - 'serial-getty@AMA0.service'
  with_items: '{{ targets }}'

- name: edit boot settings
  become: yes
  lineinfile:
    path: /boot/cmdline.txt
    backrefs: yes
    regexp: '^(.*) console=.*,115200 console=tty1 (.*)$'
    line: '\1 \2 consoleblank=0'

- name: copy splash service
  become: yes
  copy:
    dest: /etc/systemd/system/splashscreen.service
    src: ../files/splashscreen.service

- name: enable splash service
  become: yes
  systemd:
    name: splashscreen
    state: started
    daemon_reload: yes
    enabled: yes
